GET http://127.0.0.1:5000//api/getTransportFilters


###
POST http://127.0.0.1:5000/api/Filter
content-type: application/json


{
  "routes": {
    "bus": ["777"],
    "tramway": [],
    "trolleybus": [],
    "minibus": []
  },
  
  "dates": ["2024-12", "2025-03"],
  
  "timeStart": "00:00",
  "timeEnd": "23:59",
  
  "colorMode": "speed"
}

###

GET http://127.0.0.1:5000//api/getDatesFilters
